apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mutantes
  name: mutantes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutantes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mutantes
    spec:
      containers:
      - image: mutantes:1.0
        name: mutantes
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
        resources: {}
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mutantes-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mutantes-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mutantes-lbs
  name: mutantes-lbs
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: mutantes
  type: LoadBalancer
status:
  loadBalancer: {}